[build-system]
requires = ["setuptools>=45"]

[tool.coverage.run]
branch = true

[tool.isort]
profile = "black"

[tool.pydocstyle]
convention = "numpy"
add_ignore = ["D1", "D200", "D205", "D400", "D401", "D403"]
